version: '3.3'

volumes:
  data:
services:
  db:
    container_name: perguntasdb
    image: mysql:latest
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=guiaperguntas

  node:
    build: .
    command: npm start
    ports: 
      - "3000:3000"
    volumes: 
      - .:/usr/app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1